package com.cenfotec.proyectoApi.domain;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;




@DynamoDBTable(tableName = "tenfermedad")
public class Enfermedad {

		private String id;
	    private String nombre;
	    private String tipo;
	    private String medicamento ; 
	    
	    
	    @DynamoDBHashKey
	    @DynamoDBAutoGeneratedKey
	    public String getId() {
	        return id;
	    }

	    public void setId(String id) {
	        this.id = id;
	    }

	    @DynamoDBAttribute
	    public String getNombre() {
	        return nombre;
	    }

	    public void setNombre(String nombre) {
	        this.nombre = nombre;
	    }
	    
	   
	    @DynamoDBAttribute
	    public String getTipo() {
	        return tipo;
	    }

	    public void setTipo(String tipo) {
	        this.tipo = tipo;
	    }
	    
	   
	    
	    @DynamoDBAttribute
	    public String getMedicamento() {
	        return medicamento;
	    }

	    public void setMedicamento(String medicamento) {
	        this.medicamento = medicamento;
	    }
	
}
	

	
